[package]
name = "nym-macos"
description = "Abstractions for macOS"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[target.'cfg(any(target_os="macos", target_os="ios"))'.dependencies]
nix = { workspace = true, features = ["socket", "net", "ioctl"] }
tracing.workspace = true
tokio.workspace = true
